### ISSUE TITLE
Corrupted: Working example?

### ISSUE THREAD

**Issue by abpolym** [MegaAbsol/EasyCTF-2015-Writeups#1]
Hey, I tried to reproduce your easyctf/corrupted solution, but failed.

Your python script doesn't work with me - you say the value differences are over the pixel values, but the python code just calculates absolute differences over the complete file. And there are more than 231 bytes that differ in my case (same jpgs).

Can you provide a working example please?

https://github.com/MegaAbsol/EasyCTF-2015-Writeups/blob/master/Corrupted%20-%20375.md

**Comment by kevinshen100** [comment]
sorry, original image is wrong. My friend gave me the original image, and I'm sorta busy right now, but I might reupload the original image if i can find it.

That was the hardest part of the problem - finding the correct original image.

**Comment by abpolym** [comment]
@kevinshen100 Thanks, maybe I can find it too! :)

**Comment by abpolym** [comment]
@kevinshen100 Hey I've found the image and therefore solved the task, see [here](https://github.com/ctfs/write-ups-2015/tree/master/easyctf-2015/forensics/corrupted). Thanks for the hint :)
